Detalhes pedido
Mulleriano/naturau pull request #15
Opened 2023-07-13 15:07 UTC by Mulleriano

- Imagem de detalhes do pedido
- atualização do link de redirecionamento da rota de detalhes
- Criação da função para filtrar o pedido selecionado
- Criação da rota de detalhes do pedido
- Criação da composable para converter timestamp
- Criação da view de detalhes
- Criação do componente de timeline

2023-07-13 16:31 UTC, bitakamori approved these changes

2023-07-14 12:39 UTC, abimaelneto commented on src/modules/pedidos/components/Timeline.vue
> +    status.done = true;
qual a diferença entre entregue e done?

2023-07-14 12:41 UTC, abimaelneto commented on src/modules/pedidos/components/Timeline.vue
> +            status.preparo ? 'text-green-darken-4' : 'text-grey',
vocês poderiam criar uma função que, retorne essas classes baseadas no valor passado, aí poderiam reutilizar em todos os passos

```
function getStatusClass(value) {
  return value ? 'text-green-darken-4' : 'text-grey',
}
```

```suggestion
            getStatusClass(status.preparo)
```

2023-07-14 12:43 UTC, abimaelneto commented on src/modules/pedidos/composable/converterHora.js
> +    }
```suggestion
    const monthLabels = ["Jan", "Fev", "Mar", ...] // terminar aqui
    const txt = monthLabels[number]
```

2023-07-14 12:44 UTC, abimaelneto commented on src/modules/pedidos/composable/converterHora.js
> +  const dataInteira = await pedidosStore.pedido.inicio.toDate();
essa função toDate() é assincrona mesmo?

2023-07-14 12:45 UTC, abimaelneto requested changes
coloquei alguns pontos pra gente confirmar

2023-07-14 13:07 UTC, Mulleriano commented on src/modules/pedidos/components/Timeline.vue
> +    status.done = true;
O done foi uma etapa extra do status que eu criei, pra mandar para o firebase a informação de que o pedido foi concluido. Estou criando a função de criar um novo pedido e vou ajustar essa parte nessa etapa. A princípio tinha colocado pra ter controle do processo de finalizar o pedido

2023-07-14 14:17 UTC, Mulleriano commented on src/modules/pedidos/components/Timeline.vue
> +            status.preparo ? 'text-green-darken-4' : 'text-grey',
Funções criadas

2023-07-14 14:17 UTC, Mulleriano commented on src/modules/pedidos/composable/converterHora.js
> +    }
alteração feita

2023-07-14 14:18 UTC, Mulleriano commented on src/modules/pedidos/composable/converterHora.js
> +  const dataInteira = await pedidosStore.pedido.inicio.toDate();
Não é, já fiz a retirada da sintaxe

2023-07-14 14:18 UTC, Mulleriano commented
Alterações feitas @abimaelneto

2023-07-14 17:54 UTC, abimaelneto approved these changes

2023-07-14 20:02 UTC, merged