listagem restaurantes
Mulleriano/naturau pull request #6
Opened 2023-07-10 16:40 UTC by Mulleriano

- Configurando vite para github pages
- Criação da view home
- Movendo firebase.config para a pasta src
- Atualiza importação do arquivo
- Criação do layout padrão do app
- Criação da rota do aplicativo
- Criação da lista de restaurantes
- Altera nome da view e alimenta store na montagem
- Atualiza nome da view na rota
- Criação da action para receber lista de restaurantes
- Criação da store
- Criação do componente de renderização da lista

2023-07-10 18:02 UTC, bitakamori approved these changes

2023-07-10 18:56 UTC, abimaelneto commented on src/modules/restaurantes/store/index.js
> +  async getRestaurantes() {
seria legal seguir um padrão de língua - pegarRestaurantes() ou getRestaurants()

2023-07-10 18:57 UTC, abimaelneto commented on src/modules/restaurantes/views/Restaurantes.vue
> +  <RestList />
se no futuro manter só esse componente, dá pra trazer tudo de dentro dele pra view

2023-07-10 18:59 UTC, abimaelneto commented on src/router/index.js
> +            /* webpackChunkName: "home" */ "@/modules/restaurantes/views/Restaurantes.vue"
essa rota poderia ser importada usando o router local do módulo

2023-07-10 18:59 UTC, abimaelneto requested changes
quaisquer dúvidas, podem me perguntar

2023-07-11 11:59 UTC, Mulleriano commented on src/modules/restaurantes/views/Restaurantes.vue
> +  <RestList />
Pretendo criar um layout específico para essa tela, considerei fazer dessa forma pra facilitar a manutenção

2023-07-11 12:12 UTC, Mulleriano commented on src/router/index.js
> +            /* webpackChunkName: "home" */ "@/modules/restaurantes/views/Restaurantes.vue"
Aletaração realizada

2023-07-11 12:14 UTC, Mulleriano commented
Alterações realizadas

2023-07-11 14:44 UTC, abimaelneto approved these changes

2023-07-11 14:44 UTC, merged